import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => {
    sessionStorage.setItem('distribuidora.accessToken', `header.${btoa(JSON.stringify({ authorities: ['ADMIN_ALL'] }))}.signature`)
    sessionStorage.setItem('distribuidora.refreshToken', 'test-refresh-token')
  })
  await page.route(/^https?:\/\/[^/]+\/api\//, (route) => {
    const path = new URL(route.request().url()).pathname
    if (path === '/api/auth/logout') return route.fulfill({ status: 204 })
    if (path === '/api/brands' || path === '/api/categories') return route.fulfill({ json: [] })
    return route.fulfill({ json: { content: [], page: 0, size: 20, totalElements: 0, totalPages: 0 } })
  })
})

for (const width of [320, 390, 640, 760, 761, 1024, 1050, 1051, 1280, 1366, 1440, 1920]) {
  test(`navigation fits and remains usable at ${width}px`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: width === 1920 ? 1080 : 768 })
    await page.goto('/orders')
    await expect(page.getByRole('heading', { name: 'Pedidos', exact: true })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    const nav = page.getByRole('navigation', { name: 'Navegación principal' })
    if (width <= 1050) {
      await expect(nav).toHaveCount(0)
      const trigger = page.getByRole('button', { name: 'Abrir menú' })
      await trigger.click()
      const dialog = page.getByRole('dialog', { name: 'Menú principal' })
      await expect(dialog).toBeVisible()
      await expect(page.getByRole('button', { name: 'Cerrar menú' })).toBeFocused()
      await expect(page.getByRole('button', { name: 'Salir' })).toBeVisible()
      await expect(dialog.getByRole('link', { name: 'Pedidos' })).toHaveAttribute('aria-current', 'page')
      const bounds = await dialog.boundingBox()
      expect(bounds!.width).toBeLessThanOrEqual(width)
      expect(bounds!.height).toBeLessThanOrEqual(768)
      // Native modality contains keyboard focus in both directions.
      await page.keyboard.press('Shift+Tab')
      await expect(dialog.getByRole('button', { name: 'Salir' })).toBeFocused()
      await page.keyboard.press('Tab')
      await expect(dialog.getByRole('button', { name: 'Cerrar menú' })).toBeFocused()
      await page.screenshot({ path: testInfo.outputPath(`menu-${width}.png`) })
      await page.keyboard.press('Escape')
      await expect(dialog).toHaveCount(0)
      await expect(trigger).toBeFocused()
      expect(await page.evaluate(() => document.body.style.overflow)).toBe('')
      await trigger.click()
      await page.getByRole('link', { name: 'Productos', exact: true }).click()
      await expect(page).toHaveURL(/\/products$/)
      await expect(dialog).toHaveCount(0)
      await expect(page.locator('.compact-brand')).toContainText('Productos')
    } else {
      await expect(nav).toBeVisible()
      await expect(page.getByRole('button', { name: 'Abrir menú' })).toHaveCount(0)
      await nav.getByRole('link', { name: 'Auditoría' }).scrollIntoViewIfNeeded()
      await expect(nav.getByRole('link', { name: 'Auditoría' })).toBeInViewport()
      await expect(page.getByRole('button', { name: 'Salir' })).toBeInViewport()
    }
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    await page.screenshot({ path: testInfo.outputPath(`page-${width}.png`), fullPage: true })
  })
}

test('drawer supports backdrop, resize, short landscape screens and signing out', async ({ page }) => {
  await page.setViewportSize({ width: 760, height: 360 })
  await page.goto('/orders')
  const trigger = page.getByRole('button', { name: 'Abrir menú' })
  const dialog = page.getByRole('dialog', { name: 'Menú principal' })
  await trigger.click()
  await dialog.getByRole('link', { name: 'Auditoría' }).scrollIntoViewIfNeeded()
  await expect(dialog.getByRole('link', { name: 'Auditoría' })).toBeInViewport()
  await expect(dialog.getByRole('button', { name: 'Salir' })).toBeInViewport()
  await page.mouse.click(740, 180)
  await expect(dialog).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await trigger.click()
  await page.setViewportSize({ width: 1280, height: 720 })
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Pedidos', exact: true })).toBeFocused()
  expect(await page.evaluate(() => document.body.style.overflow)).toBe('')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(dialog).toHaveCount(0)
  await trigger.click()
  await dialog.getByRole('link', { name: 'Productos', exact: true }).click()
  await trigger.click()
  await page.goBack()
  await expect(page).toHaveURL(/\/orders$/)
  await expect(dialog).toHaveCount(0)
  await trigger.click()
  await dialog.getByRole('button', { name: 'Salir' }).click()
  await expect(page).toHaveURL(/\/login$/)
  await expect(page.getByRole('heading', { name: 'Ingresar' })).toBeVisible()
  expect(await page.evaluate(() => document.body.style.overflow)).toBe('')
})

test('compact navigation respects permissions and reduced motion', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/orders')
  await page.evaluate(() => sessionStorage.setItem('distribuidora.accessToken', `header.${btoa(JSON.stringify({ authorities: ['SELLER'] }))}.signature`))
  // Init scripts reset the session on reload, so use an in-app route transition.
  await page.getByRole('button', { name: 'Abrir menú' }).click()
  await page.getByRole('link', { name: 'Ventas', exact: true }).click()
  await page.getByRole('button', { name: 'Abrir menú' }).click()
  const dialog = page.getByRole('dialog', { name: 'Menú principal' })
  await expect(dialog.getByRole('link', { name: 'Resumen' })).toHaveCount(0)
  await expect(dialog.getByRole('link', { name: 'Usuarios' })).toHaveCount(0)
  await expect(dialog.getByRole('link', { name: 'Clientes' })).toHaveCount(0)
  for (const name of ['Productos', 'Marcas y categorías', 'Listas de precios']) {
    await expect(dialog.getByRole('link', { name })).toHaveCount(0)
  }
  await expect(dialog.getByText('Catálogo', { exact: true })).toHaveCount(0)
  await expect(dialog.getByRole('link', { name: 'Pedidos' })).toBeVisible()
  await page.getByRole('button', { name: 'Cerrar menú' }).click()
  await expect(dialog).toHaveCount(0)
})
