import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => sessionStorage.setItem('distribuidora.accessToken', `header.${btoa(JSON.stringify({ authorities: ['ADMIN_ALL'] }))}.signature`))
  await page.route(/^https?:\/\/[^/]+\/api\//, async (route) => {
    const url = new URL(route.request().url())
    const pageNumber = Number(url.searchParams.get('page') ?? 0)
    const paged = (content: unknown[], totalPages = 1) => ({ content, page: pageNumber, size: 100, totalPages, totalElements: content.length * totalPages })
    if (url.pathname === '/api/suppliers') return route.fulfill({ json: paged([{ id: pageNumber ? 'supplier-a' : 'supplier-b', name: pageNumber ? 'Proveedor Norte' : 'Proveedor Sur' }], 2) })
    if (url.pathname === '/api/products') return route.fulfill({ json: paged([{ id: 'product-a', name: 'Molino Norte Harina', description: 'Harina', brandId: 'brand', categoryId: 'category', cost: 20, status: 'ACTIVE', suppliers: [{ id: 'supplier-a', name: 'Proveedor Norte' }] }]) })
    if (url.pathname === '/api/pricing/lists') return route.fulfill({ json: paged([{ id: 'list', code: 'GENERAL', name: 'General', status: 'ACTIVE' }]) })
    if (url.pathname === '/api/categories') return route.fulfill({ json: [{ id: 'category', name: 'Almacén', status: 'ACTIVE' }] })
    if (url.pathname === '/api/brands') return route.fulfill({ json: [{ id: 'brand', name: 'Molino Norte', status: 'ACTIVE' }] })
    const order = { id: 'order-a', number: 'PRV-00000001', supplierId: 'supplier-a', supplier: 'Proveedor Norte', date: '2026-09-01', total: 75 }
    const items = [{ productId: 'product-a', productName: 'Molino Norte Harina', quantity: 3, unitCost: 10, lineTotal: 30, currentCost: 25, status: 'ACTIVE' }]
    if (url.pathname.endsWith('/last-order')) return route.fulfill({ json: url.pathname.includes('supplier-a') ? { available: true, order, items } : { available: false } })
    if (url.pathname === '/api/supplier-orders' && route.request().method() === 'POST') return route.fulfill({ status: 201, json: { id: 'order-a', number: 'PRV-00000001', total: 75 } })
    if (url.pathname === '/api/supplier-orders') return route.fulfill({ json: paged([order]) })
    if (url.pathname === '/api/supplier-orders/order-a') return route.fulfill({ json: { order, items } })
    if (route.request().method() === 'PUT') return route.fulfill({ status: 204 })
    return route.fulfill({ json: paged([]) })
  })
})

for (const width of [320, 760, 1440]) {
  test(`supplier requests, previous order and date filters work at ${width}px`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/supplier-orders')
    await expect(page.getByRole('heading', { name: 'Pedidos a proveedores', exact: true })).toBeVisible()
    if (width <= 1050) await page.getByRole('button', { name: 'Abrir menú' }).click()
    const links = await page.getByRole('navigation').getByRole('link').allTextContents()
    expect(links.indexOf('Pedidos a proveedores')).toBe(links.indexOf('Ventas') + 1)
    expect(links.indexOf('Clientes')).toBe(links.indexOf('Pedidos a proveedores') + 1)
    if (width <= 1050) await page.keyboard.press('Escape')
    await page.getByRole('button', { name: '+ Nuevo pedido a proveedor' }).click()
    const supplier = page.getByRole('combobox', { name: 'Proveedor', exact: true })
    await expect(supplier).toBeEnabled()
    await supplier.fill('Norte')
    await page.getByRole('option', { name: 'Proveedor Norte', exact: true }).click()
    const previous = page.getByRole('button', { name: 'Cargar pedido anterior' })
    await expect(previous).toBeEnabled()
    await previous.click()
    await expect(page.getByLabel('Cantidad de Molino Norte Harina')).toHaveValue('3')
    await expect(page.getByLabel('Costo de Molino Norte Harina')).toHaveValue('25')
    await expect(page.getByRole('button', { name: 'Solicitar pedido' })).toBeEnabled()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: info.outputPath(`purchase-form-${width}.png`), fullPage: true })
    const request = page.waitForRequest((request) => request.method() === 'POST' && new URL(request.url()).pathname === '/api/supplier-orders')
    await page.getByRole('button', { name: 'Solicitar pedido' }).click()
    expect((await request).postDataJSON()).toMatchObject({ supplierId: 'supplier-a', lines: [{ productId: 'product-a', quantity: 3, unitCost: 25 }] })
    await expect(page.getByText('Pedido PRV-00000001 registrado correctamente.', { exact: false })).toBeVisible()
    await page.getByRole('button', { name: 'Abrir calendario: Desde' }).click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Abrir calendario: Desde' })).toBeFocused()
    await page.getByRole('link', { name: 'Ver pedido PRV-00000001', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'PRV-00000001' })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  })
  test(`optional product supplier associations remain usable at ${width}px`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/products')
    await page.getByRole('button', { name: 'Editar Molino Norte Harina', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Quitar proveedor Proveedor Norte' })).toBeVisible()
    const suppliers = page.getByRole('combobox', { name: 'Proveedores (opcional)' })
    await expect(suppliers).toBeEnabled()
    await suppliers.fill('Sur')
    await page.getByRole('option', { name: 'Proveedor Sur' }).click()
    await page.getByRole('button', { name: 'Quitar proveedor Proveedor Norte' }).click()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: info.outputPath(`product-suppliers-${width}.png`), fullPage: true })
    const request = page.waitForRequest((request) => request.method() === 'PUT')
    await page.getByRole('button', { name: 'Guardar cambios', exact: true }).click()
    expect((await request).postDataJSON().supplierIds).toEqual(['supplier-b'])
  })
}
