import { expect, test } from '@playwright/test'

test('sale filters combine, persist and remain accessible on mobile', async ({ page }, testInfo) => {
  await page.clock.setFixedTime(new Date('2026-09-30T12:00:00Z'))
  await page.addInitScript(() => sessionStorage.setItem('distribuidora.accessToken', 'test-access-token'))
  const requests: URL[] = []
  await page.route('**/api/sales/filter-options', async (route) => route.fulfill({ json: {
    customers: [{ id: 'customer-1', name: 'Almacén Norte' }, { id: 'customer-2', name: 'Mercado Sur' }],
    sellers: [{ id: 'seller-1', name: 'Ana' }, { id: 'seller-2', name: 'Lucía' }],
  } }))
  await page.route('**/api/sales?*', async (route) => {
    const url = new URL(route.request().url())
    requests.push(url)
    const currentPage = Number(url.searchParams.get('page'))
    await route.fulfill({ json: {
      content: [{ id: `sale-${currentPage}`, number: `SAL-${currentPage}`, customer: 'Almacén Norte', total: 300, paid: 100, balance: 200, status: 'CONFIRMED', date: '2026-09-30T12:00:00Z' }],
      page: currentPage, size: 20, totalElements: 21, totalPages: 2,
    } })
  })
  await page.goto('/sales')
  const number = page.getByLabel('Buscar ventas', { exact: true })
  const customer = page.getByRole('combobox', { name: 'Buscar por cliente' })
  const seller = page.getByRole('combobox', { name: 'Buscar por vendedor' })
  const pending = page.getByRole('combobox', { name: 'Saldo pendiente', exact: true })
  const min = page.getByLabel('Fecha mín.', { exact: true })
  const max = page.getByLabel('Fecha máx.', { exact: true })
  await expect(customer).toBeEnabled()
  await expect(seller).toBeEnabled()
  await expect(min).toHaveValue('')
  await expect(max).toHaveValue('')
  await expect(number).toHaveAttribute('placeholder', 'Número de venta')
  await number.focus()
  expect(await number.evaluate((input) => Number.parseFloat(getComputedStyle(input).outlineWidth))).toBeGreaterThan(0)
  await page.keyboard.press('Tab')
  await expect(customer).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(seller).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(pending).toBeFocused()
  await number.fill('SAL')
  await expect.poll(() => requests.at(-1)?.searchParams.get('search')).toBe('SAL')
  await customer.click()
  await customer.pressSequentially('almacen')
  await expect(page.getByRole('option', { name: 'Almacén Norte' })).toBeVisible()
  await expect(page.getByRole('option', { name: 'Mercado Sur' })).toHaveCount(0)
  expect(requests.at(-1)?.searchParams.get('customerId')).toBe('')
  await page.screenshot({ path: testInfo.outputPath('sales-name-search.png') })
  await customer.press('ArrowDown')
  await customer.press('ArrowDown')
  await customer.press('Enter')
  await expect.poll(() => requests.at(-1)?.searchParams.get('customerId')).toBe('customer-1')
  await seller.fill('LUCIA')
  await page.getByRole('option', { name: 'Lucía', exact: true }).click()
  await expect.poll(() => requests.at(-1)?.searchParams.get('sellerId')).toBe('seller-2')
  await pending.selectOption('true')
  await expect.poll(() => requests.at(-1)?.searchParams.get('pendingBalance')).toBe('true')
  expect(requests.at(-1)?.searchParams.get('search')).toBe('SAL')
  expect(requests.at(-1)?.searchParams.get('customerId')).toBe('customer-1')
  expect(requests.at(-1)?.searchParams.get('sellerId')).toBe('seller-2')
  await min.fill('01/09/2026')
  await expect.poll(() => requests.at(-1)?.searchParams.get('dateMin')).toBe('2026-09-01')
  await max.fill('30/09/2026')
  await expect.poll(() => requests.at(-1)?.searchParams.get('dateMax')).toBe('2026-09-30')
  await page.getByRole('button', { name: 'Abrir calendario: Fecha mín.' }).click()
  const calendar = page.getByRole('dialog', { name: /Calendario: Fecha mín./ })
  await expect(calendar).toBeVisible()
  await expect(calendar.getByRole('heading')).toHaveText('Septiembre de 2026')
  const calendarBox = await calendar.boundingBox()
  expect(calendarBox!.x).toBeGreaterThanOrEqual(0)
  expect(calendarBox!.x + calendarBox!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
  await page.screenshot({ path: testInfo.outputPath('sales-calendar.png') })
  await calendar.getByRole('button', { name: /\bmiércoles,? 2 de septiembre de 2026/ }).click()
  await expect(min).toHaveValue('02/09/2026')
  await expect.poll(() => requests.at(-1)?.searchParams.get('dateMin')).toBe('2026-09-02')
  await expect(page.getByRole('button', { name: 'Abrir calendario: Fecha mín.' })).toBeFocused()
  await expect(page.getByText('SAL-0', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Siguiente' }).click()
  await expect(page.getByText('SAL-1', { exact: true })).toBeVisible()
  expect(requests.at(-1)?.searchParams.get('pendingBalance')).toBe('true')
  await customer.fill('sur')
  await page.getByRole('option', { name: 'Mercado Sur' }).click()
  await expect.poll(() => requests.at(-1)?.searchParams.get('customerId')).toBe('customer-2')
  expect(requests.at(-1)?.searchParams.get('page')).toBe('0')
  await page.reload()
  await expect(number).toHaveValue('SAL')
  await expect(customer).toHaveValue('Mercado Sur')
  await expect(seller).toHaveValue('Lucía')
  await customer.fill('no existe')
  await expect(page.getByText('No se encontraron coincidencias.')).toBeVisible()
  await customer.press('Escape')
  await expect(customer).toHaveValue('Mercado Sur')
  await expect(customer).toHaveAttribute('aria-expanded', 'false')
  await expect(pending).toHaveValue('true')
  await expect(min).toHaveValue('02/09/2026')
  await expect(max).toHaveValue('30/09/2026')
  const widths = await page.evaluate(() => ({ viewport: innerWidth, document: document.documentElement.scrollWidth }))
  expect(widths.document).toBeLessThanOrEqual(widths.viewport)
  if (page.viewportSize()!.width <= 640) {
    const fields = await Promise.all([number, customer, seller, pending].map((field) => field.boundingBox()))
    for (let index = 1; index < fields.length; index++) {
      expect(fields[index]!.y).toBeGreaterThan(fields[index - 1]!.y + fields[index - 1]!.height)
      expect(fields[index]!.width).toBeCloseTo(fields[0]!.width, 0)
    }
  }
  await page.screenshot({ path: testInfo.outputPath('sales-filters.png'), fullPage: true })
  await pending.selectOption('')
  await expect.poll(() => requests.at(-1)?.searchParams.get('pendingBalance')).toBe('false')
  await max.focus()
  await page.keyboard.press('Enter')
  const maxCalendar = page.getByRole('dialog', { name: /Calendario: Fecha máx./ })
  await expect(maxCalendar).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(max).toBeFocused()
  await min.fill('01/10/2026')
  await expect(page.getByRole('alert')).toContainText('La fecha mínima no puede ser posterior')
  await min.fill('31/09/2026')
  await expect(page.getByRole('alert')).toContainText('Las fechas deben ser válidas')
  await min.fill('')
  await expect.poll(() => requests.at(-1)?.searchParams.get('dateMin')).toBe('')
  await max.fill('')
  await expect.poll(() => requests.at(-1)?.searchParams.get('dateMax')).toBe('')
})
